apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: ashadur/train-schedule:latest
        ports:
        - containerPort: 3000
