apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
